apiVersion: apps/v1
kind: Deployment
metadata:
  name: xreds
  labels:
    app: xreds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xreds

  template:
    metadata:
      labels:
        app: xreds
    spec:
      containers:
      - name: xreds
        image: us-central1-docker.pkg.dev/camus-infra/xreds/xreds:latest
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: "4"
            ephemeral-storage: 10Gi
            memory: 8Gi
        ports:
        - containerPort: 8080
        env:
        - name: datasets_mapping_file
          value: "/opt/xreds/datasets/camus_datasets.json"
---
apiVersion: v1
kind: Service
metadata:
  name: xreds-service
  labels:
    app: xreds
  annotations:
    grid.dev/camus_external_name: xreds
spec:
  selector:
    app.kubernetes.io/name: xreds
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: xreds